version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile-app
    expose:
      - 5000

  apache:
    build:
      context: ./apache
      dockerfile: Dockerfile-apache
    environment:
      - APACHE_LOG_DIR=/usr/local/apache2/logs
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - app
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /etc/ssl/keys:/etc/ssl/keys:ro
      - /var/log:/var/log:ro # mount host /var/log to container
