FROM httpd:2.4
LABEL authors="chase"

# enable proxy modules
RUN sed -i \
    -e 's/#LoadModule proxy_module modules\/mod_proxy.so/LoadModule proxy_module modules\/mod_proxy.so/' \
    -e 's/#LoadModule proxy_http_module modules\/mod_proxy_http.so/LoadModule proxy_http_module modules\/mod_proxy_http.so/' \
    /usr/local/apache2/conf/httpd.conf

# copy Apache config
COPY ./myapp.conf /usr/local/apache2/conf/myapp.conf

# enable SSL module
RUN sed -i 's/#LoadModule ssl_module modules\/mod_ssl.so/LoadModule ssl_module modules\/mod_ssl.so/' /usr/local/apache2/conf/httpd.conf

# include myapp.conf in the main apache config
RUN echo "Include /usr/local/apache2/conf/myapp.conf" \
    >> /usr/local/apache2/conf/httpd.conf


