FROM httpd:2.4
LABEL authors="chase"
WORKDIR /apache
# dependencies for apache and wsgi
RUN apt-get update && apt-get install -y \
    build-essential \
    libapache2-mod-wsgi-py3 \
    python:3.10-slim \
    python3-pip \
    python3-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY myapp.conf /usr/local/apache2/conf/sites-available/myapp.conf
COPY ../myapp.wsgi /app/myapp.wsgi

# python dependencies for app, not sure if needed
COPY requirements.txt /tmp/
RUN pip3 install -r /tmp/requirements.txt
